# Generated by Django 3.2.17 on 2023-02-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_versions_field'),
        ('ansible', '0046_add_fulltext_search_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigstoreSigningService',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ansible_sigstoresigningservice', serialize=False, to='core.content')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('rekor_url', models.TextField(default='https://rekor.sigstore.dev')),
                ('rekor_root_pubkey', models.TextField(null=True)),
                ('oidc_issuer', models.TextField(default='https://oauth2.sigstore.dev')),
                ('fulcio_url', models.TextField(default='https://fulcio.sigstore.dev')),
                ('oidc_client_id', models.CharField(max_length=64)),
                ('oidc_client_secret', models.CharField(max_length=64)),
                ('ctfe', models.TextField(null=True)),
                ('cert_identity', models.TextField()),
                ('verify_offline', models.BooleanField(null=True)),
                ('sigstore_bundle', models.BooleanField(null=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
        migrations.AddField(
            model_name='ansiblerepository',
            name='sigstore_signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ansible_repositories', to='ansible.sigstoresigningservice'),
        ),
        migrations.CreateModel(
            name='CollectionVersionSigstoreSignature',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ansible_collectionversionsigstoresignature', serialize=False, to='core.content')),
                ('data', models.BinaryField()),
                ('digest', models.CharField(max_length=64)),
                ('sigstore_x509_certificate', models.BinaryField()),
                ('sigstore_x509_certificate_sha256_digest', models.CharField(max_length=64)),
                ('sigstore_bundle', models.TextField(null=True)),
                ('signed_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigstore_signatures', to='ansible.collectionversion')),
                ('sigstore_signing_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sigstore_signatures', to='ansible.sigstoresigningservice')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('sigstore_x509_certificate_sha256_digest', 'signed_collection')},
            },
            bases=('core.content',),
        ),
    ]
