# Generated by Django 3.2.16 on 2023-01-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0047_sigstore_signature_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigstoresigningservice',
            name='name',
            field=models.TextField(db_index=True, default='default_sigstore_signing_service_name', unique=True),
            preserve_default=False,
        ),
    ]
